name: dermascan_ai
description: DermaScan AI - Offline-First Skin Cancer Screening & Referral Mobile App

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Offline TFLite Inference
  tflite_flutter: ^0.12.0
  image: ^4.1.7
  
  # Hindi Voice Guidance (TTS)
  flutter_tts: ^4.2.5
  
  # Camera & Storage
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Offline Referral Queue & Sync
  sqflite: ^2.3.2
  connectivity_plus: ^6.1.0
  http: ^1.2.0

  # Real Location & GPS
  geolocator: ^10.1.0
  shared_preferences: ^2.5.5
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model/best_int8.tflite
    - assets/labels.txt
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"